console.log(Infinity + NaN)
console.log(Infinity - NaN)
console.log(Infinity * NaN)
console.log(Infinity / NaN)
console.log(-Infinity + NaN)
console.log(-Infinity - NaN)
console.log(-Infinity * NaN)
console.log(-Infinity / NaN)